In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("spam.csv", encoding='latin1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
df= df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

In [ ]:
df.v1.value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam']= df['v1'].apply(lambda x: 1 if x=='spam' else 0)

In [ ]:
df.head()

     v1                                                 v2  spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
df.rename(columns={'v2':'message', 'v1':'category'}, inplace=True)

In [ ]:
df.head()

  Category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(df.message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v= CountVectorizer()

In [ ]:
X_train_cv= v.fit_transform(X_train.values)
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_cv.shape

(4457, 7710)

In [ ]:
v.get_feature_names_out().shape

(7710,)

In [ ]:
v.vocabulary_

{'we': 7362,
 'not': 4811,
 'watching': 7345,
 'movie': 4584,
 'already': 920,
 'xy': 7612,
 'wants': 7325,
 'shop': 6065,
 'so': 6237,
 'shopping': 6067,
 'her': 3400,
 'now': 4823,
 'ì_': 7699,
 'wan': 7316,
 'to': 6883,
 'go': 3160,
 'there': 6782,
 'doctor': 2383,
 'gr8': 3214,
 'new': 4738,
 'service': 5988,
 'live': 4136,
 'sex': 5999,
 'video': 7224,
 'chat': 1741,
 'on': 4916,
 'your': 7659,
 'mob': 4519,
 'see': 5944,
 'the': 6765,
 'sexiest': 6000,
 'dirtiest': 2340,
 'girls': 3140,
 'ur': 7148,
 'phone': 5160,
 'details': 2276,
 'text': 6735,
 'horny': 3490,
 '89070': 704,
 'cancel': 1623,
 'send': 5970,
 'stop': 6444,
 'hello': 3387,
 'which': 7440,
 'site': 6145,
 'download': 2433,
 'songs': 6271,
 'its': 3747,
 'urgent': 7151,
 'pls': 5232,
 'wen': 7405,
 'miss': 4487,
 'someone': 6255,
 'mm': 4508,
 'that': 6759,
 'time': 6852,
 'you': 7654,
 'dont': 2413,
 'like': 4093,
 'fun': 3040,
 'did': 2300,
 'he': 3359,
 'just': 3859,
 'say': 5889,
 'somebody': 6253,
 'is': 3731,
 'named': 4667,
 'tampa': 6654,
 'sorry': 6283,
 'll': 4144,
 'call': 1595,
 'later': 4012,
 'take': 6640,
 'care': 1644,
 'and': 956,
 'sleep': 6174,
 'well': 7402,
 'need': 4707,
 'learn': 4040,
 'change': 1720,
 'in': 3630,
 'life': 4082,
 'only': 4928,
 'get': 3116,
 'convinced': 2003,
 'will': 7470,
 'wait': 7296,
 'but': 1565,
 'no': 4775,
 'more': 4561,
 'conversations': 1998,
 'between': 1323,
 'us': 7161,
 'by': 1580,
 'family': 2768,
 'over': 5007,
 'for': 2938,
 'many': 4327,
 'senses': 5976,
 'respect': 5706,
 'them': 6773,
 'overemphasise': 5010,
 'or': 4956,
 'have': 3348,
 'role': 5781,
 'my': 4645,
 'aiyah': 885,
 'ok': 4895,
 'wat': 7340,
 'as': 1078,
 'long': 4176,
 'got': 3200,
 'improve': 3627,
 'can': 1619,
 '85233': 680,
 'free': 2985,
 'ringtone': 5759,
 'reply': 5681,
 'real': 5568,
 'sac': 5834,
 'score': 5906,
 'big': 1334,
 'hundred': 3540,
 'set': 5992,
 'batsman': 1245,
 'am': 931,
 'way': 7357,
 'home': 3463,
 'win': 7473,
 'winner': 7482,
 'mr': 4590,
 'foley': 2917,
 'won': 7526,
 'an': 952,
 'ipod': 3721,
 'exciting': 2699,
 'prizes': 5391,
 'soon': 6275,
 'keep': 3890,
 'eye': 2739,
 'mobile': 4521,
 'visit': 7248,
 'www': 7589,
 '82050': 650,
 'co': 1871,
 'uk': 7070,
 'lar': 3999,
 'jus': 3858,
 'testing': 6730,
 'card': 1640,
 'dunno': 2495,
 'network': 4731,
 'gd': 3095,
 'thk': 6804,
 'me': 4386,
 'waiting': 7299,
 'sis': 6141,
 'finish': 2858,
 'bathing': 1244,
 'bathe': 1243,
 'dun': 2493,
 'disturb': 2362,
 'liao': 4073,
 'cleaning': 1835,
 'room': 5788,
 'yetunde': 7642,
 'class': 1828,
 'run': 5822,
 'water': 7347,
 'it': 3740,
 'make': 4305,
 'hi': 3415,
 'lou': 4206,
 'took': 6922,
 'left': 4048,
 'at': 1105,
 'friends': 3007,
 'lancaster': 3983,
 'bak': 1202,
 'neway': 4739,
 'im': 3605,
 'couldnåõt': 2039,
 'båõday': 1582,
 'hun': 3539,
 'customer': 2130,
 'annoncement': 970,
 'years': 7628,
 'delivery': 2240,
 'please': 5225,
 '07046744435': 21,
 'arrange': 1067,
 'also': 923,
 'was': 7334,
 'awesome': 1164,
 'don': 2410,
 'regular': 5641,
 'unless': 7117,
 'person': 5136,
 'happy': 3330,
 'year': 7627,
 'mean': 4388,
 'intrude': 3704,
 'let': 4066,
 'know': 3941,
 'how': 3511,
 'much': 4613,
 'tuition': 7020,
 'paid': 5035,
 'last': 4006,
 'semester': 5966,
 'this': 6803,
 'thanks': 6751,
 'love': 4212,
 'aathi': 744,
 'lot': 4200,
 'yes': 7637,
 'be': 1265,
 'glad': 3147,
 'made': 4283,
 'lor': 4192,
 'thanx': 6756,
 'ìï': 7701,
 'school': 5902,
 'if': 3590,
 'timing': 6856,
 'then': 6777,
 'looks': 4185,
 'scrumptious': 5920,
 'daddy': 2150,
 'eat': 2522,
 'all': 907,
 'night': 4757,
 'oh': 4892,
 'fuck': 3027,
 'sake': 5846,
 'she': 6033,
 'tallahassee': 6653,
 'interflora': 3697,
 'åòit': 7696,
 'too': 6921,
 'late': 4009,
 'order': 4964,
 'flowers': 2907,
 'christmas': 1809,
 '0800': 47,
 '505060': 534,
 'place': 5203,
 'before': 1291,
 'midnight': 4449,
 'tomorrow': 6908,
 'join': 3823,
 'horniest': 3489,
 'dogging': 2396,
 '2nite': 406,
 'sign': 6113,
 'up': 7131,
 'follow': 2919,
 'instructions': 3688,
 'txt': 7042,
 'entry': 2617,
 '69888': 589,
 'nyt': 4852,
 'ec2a': 2527,
 '3lp': 462,
 'msg': 4595,
 '150p': 309,
 'best': 1316,
 'line': 4108,
 'said': 5845,
 'till': 6850,
 'day': 2184,
 'forget': 2945,
 'realize': 5573,
 'cannot': 1630,
 'gn': 3157,
 'hey': 3410,
 've': 7203,
 'booked': 1417,
 'pilates': 5189,
 'yoga': 7650,
 'lesson': 4064,
 'haha': 3292,
 'do': 2377,
 'what': 7425,
 'mallika': 4314,
 'sherawat': 6039,
 'yesterday': 7639,
 'find': 2852,
 'out': 4992,
 'lt': 4232,
 'url': 7157,
 'gt': 3258,
 'message': 4434,
 'activate': 798,
 '500': 532,
 'messages': 4436,
 'replying': 5682,
 'with': 7498,
 'word': 7541,
 'terms': 6721,
 'conditions': 1958,
 '07781482378': 30,
 'com': 1905,
 'directly': 2336,
 'behind': 1299,
 'abt': 764,
 'rows': 5803,
 'per': 5124,
 'request': 5688,
 'from': 3020,
 'rs': 5809,
 'has': 3339,
 'been': 1285,
 'transfered': 6966,
 'light': 4090,
 'turned': 7027,
 'green': 3241,
 'meant': 4393,
 'another': 976,
 'friend': 3006,
 'wanted': 7323,
 'worth': 7556,
 'may': 4377,
 'around': 1065,
 'hiya': 3438,
 'hows': 3516,
 'going': 3173,
 'sunny': 6548,
 'africa': 848,
 'hope': 3480,
 'avin': 1154,
 'good': 3184,
 'give': 3143,
 'old': 4908,
 'silver': 6122,
 'back': 1189,
 'kiss': 3930,
 'bus': 1558,
 'pick': 5175,
 'bought': 1440,
 'eggs': 2553,
 'dear': 2196,
 'are': 1044,
 'our': 4989,
 'rubber': 5815,
 'found': 2967,
 'diff': 2311,
 'farm': 2779,
 'buy': 1569,
 'some': 6251,
 'cheese': 1761,
 'north': 4805,
 'carolina': 1658,
 'texas': 6733,
 'atm': 1112,
 'would': 7562,
 'gre': 3236,
 'pay': 5098,
 'test': 6729,
 'results': 5723,
 'sent': 5978,
 'pa': 5025,
 'had': 3290,
 'lunch': 4243,
 'aha': 871,
 'kate': 3883,
 'lovely': 4214,
 'tonight': 6917,
 'ill': 3602,
 'sing': 6132,
 'guy': 3279,
 'gave': 3086,
 'his': 3430,
 'xxx': 7606,
 'argh': 1052,
 '3g': 458,
 'spotty': 6365,
 'anyway': 997,
 'thing': 6792,
 'remember': 5653,
 'research': 5693,
 'province': 5442,
 'sterling': 6425,
 'were': 7411,
 'problem': 5396,
 'places': 5206,
 'looked': 4182,
 'mathews': 4362,
 'tait': 6637,
 'edwards': 2543,
 'anderson': 957,
 're': 5556,
 'welcome': 7400,
 'caught': 1679,
 'using': 7172,
 'broken': 1512,
 'english': 2601,
 'again': 857,
 'jetton': 3807,
 'ave': 1150,
 'forgot': 2950,
 'er': 2626,
 'mw': 4643,
 'filled': 2839,
 'tuth': 7030,
 'aight': 877,
 'bothering': 1437,
 'trust': 7004,
 'answers': 982,
 'guaranteed': 3261,
 '200': 348,
 'award': 1161,
 'even': 2661,
 '1000': 264,
 'cashto': 1670,
 'claim': 1821,
 '08000407165': 48,
 '18': 324,
 'getstop': 3122,
 '88222': 699,
 'php': 5169,
 'rg21': 5741,
 '4jx': 517,
 'sad': 5838,
 'one': 4922,
 'about': 757,
 'past': 5087,
 'morning': 4564,
 'continent': 1991,
 'yeah': 7626,
 'usual': 7174,
 'of': 4872,
 'town': 6950,
 'definitely': 2225,
 'people': 5123,
 'lol': 4169,
 'tmr': 6877,
 'maybe': 4379,
 'meet': 4404,
 'yck': 7625,
 'valentine': 7186,
 'game': 3067,
 'dis': 2342,
 'same': 5859,
 'really': 5576,
 'loves': 4219,
 'ques': 5496,
 'colour': 1903,
 'suits': 6536,
 'rply': 5807,
 'thx': 6837,
 'few': 2819,
 'months': 4557,
 'great': 3237,
 'yourself': 7664,
 'beautiful': 1271,
 'sounds': 6294,
 'crazy': 2070,
 'tahan': 6635,
 'anot': 975,
 'small': 6198,
 'prestige': 5367,
 'needs': 4711,
 'bed': 1281,
 'fucking': 3030,
 'dealing': 2194,
 'think': 6794,
 'cant': 1631,
 'display': 2359,
 'texts': 6745,
 'still': 6433,
 'want': 7321,
 'number': 4839,
 'type': 7055,
 'food': 2928,
 'prepare': 5353,
 'pounded': 5313,
 'every': 2668,
 'sat': 5877,
 'intro': 3703,
 'kickboxing': 3910,
 'goodmorning': 3188,
 'today': 6890,
 'min': 4461,
 'raining': 5520,
 'mah': 4293,
 'hard': 3331,
 'leave': 4042,
 'orchard': 4963,
 'txting': 7048,
 'driving': 2464,
 'popped': 5283,
 'ask': 1085,
 'bout': 1443,
 'something': 6259,
 'tonght': 6915,
 'girl': 3137,
 'comes': 1913,
 'nervous': 4723,
 'welp': 7404,
 'sort': 6284,
 'semiobscure': 5968,
 'internet': 3699,
 'write': 7571,
 'put': 5479,
 'dictionary': 2299,
 'mode': 4531,
 'cover': 2050,
 'screen': 5917,
 'hand': 3307,
 'press': 5364,
 'gently': 3109,
 'remove': 5663,
 'interesting': 3696,
 'bath': 1242,
 'hair': 3296,
 'come': 1911,
 'when': 7432,
 'done': 2411,
 'looking': 4184,
 'forward': 2963,
 'cuddling': 2113,
 'two': 7041,
 'sleeps': 6178,
 'hamster': 3306,
 'dead': 2191,
 '1pm': 339,
 'mrt': 4593,
 'brum': 1526,
 'putting': 5482,
 'keeping': 3891,
 'brainless': 1469,
 'baby': 1183,
 'doll': 2406,
 'vehicle': 7207,
 'sariyag': 5875,
 'drive': 2461,
 'madoke': 4284,
 'barolla': 1228,
 'missionary': 4492,
 'hook': 3476,
 'doggy': 2397,
 'standing': 6395,
 'yup': 7678,
 'noe': 4779,
 'leh': 4054,
 'means': 4392,
 'fat': 2786,
 'head': 3360,
 'except': 2697,
 'theres': 6783,
 'chick': 1773,
 'huge': 3531,
 'boobs': 1415,
 'online': 4926,
 'reach': 5557,
 'ard': 1043,
 '20': 347,
 'mins': 4475,
 'early': 2512,
 'bird': 1347,
 'any': 986,
 'purchases': 5469,
 'yet': 7640,
 'yogasana': 7651,
 'coz': 2052,
 'end': 2588,
 'cine': 1815,
 'hav': 3346,
 'steam': 6418,
 'thankyou': 6755,
 'appreciate': 1023,
 'feeling': 2805,
 'sick': 6107,
 'yep': 7635,
 'derek': 2261,
 'house': 3506,
 'sunday': 6545,
 'allo': 912,
 'braved': 1475,
 'buses': 1560,
 'taken': 6642,
 'trains': 6961,
 'triumphed': 6991,
 'ham': 3305,
 'jolly': 3831,
 'rest': 5715,
 'week': 7386,
 'could': 2036,
 'blake': 1366,
 'address': 811,
 'occurs': 4868,
 'quite': 5503,
 'sure': 6571,
 'doing': 2402,
 'thought': 6814,
 'whats': 7427,
 'plan': 5208,
 'coming': 1916,
 'dinner': 2330,
 'rite': 5767,
 'dad': 2149,
 'confirm': 1964,
 'wif': 7460,
 'bbq': 1253,
 'mine': 4466,
 '6ish': 596,
 'nope': 4796,
 'sch': 5900,
 'fri': 3001,
 'cos': 2024,
 'mys': 4648,
 'paper': 5052,
 'da': 2145,
 'morn': 4562,
 'list': 4124,
 'buyers': 1571,
 'nt': 4830,
 'joking': 3830,
 'seriously': 5986,
 'told': 6900,
 'evening': 2662,
 'bit': 1354,
 'bloody': 1390,
 'babyjontet': 1185,
 'eta': 2651,
 'taunton': 6668,
 '12': 284,
 '30': 423,
 'planned': 5212,
 'okday': 4897,
 'xx': 7603,
 'sports': 6362,
 'fans': 2774,
 'latest': 4013,
 'news': 4742,
 'str': 6456,
 'wk': 7507,
 'plus': 5236,
 'tone': 6910,
 'sport': 6361,
 '8007': 635,
 'getzed': 3125,
 '0870141701216': 79,
 'norm': 4801,
 '4txt': 524,
 '120p': 286,
 'where': 7435,
 'company': 1927,
 'very': 7216,
 'environment': 2621,
 'terrific': 6725,
 'nice': 4750,
 'nobody': 4778,
 'names': 4668,
 'their': 6770,
 'penis': 5121,
 'name': 4664,
 'story': 6455,
 'doesn': 2389,
 'add': 805,
 'who': 7446,
 'talking': 6651,
 'issues': 3739,
 'right': 5750,
 'fix': 2876,
 'mate': 4357,
 'haunt': 3345,
 'stuff': 6489,
 'sorted': 6286,
 'sound': 6292,
 'promoting': 5424,
 'hex': 3409,
 'joke': 3826,
 '146tf150p': 304,
 'talk': 6648,
 'atleast': 1111,
 'once': 4920,
 'otherwise': 4983,
 'world': 7548,
 'shakespeare': 6017,
 'shesil': 6041,
 'saying': 5891,
 'should': 6078,
 'slippers': 6187,
 'returning': 5731,
 'away': 1163,
 'trek': 6983,
 'sweater': 6597,
 'fr': 2974,
 'mango': 4324,
 'size': 6154,
 'irritating': 3730,
 'staff': 6385,
 'taking': 6645,
 'course': 2047,
 'nothing': 4815,
 'happen': 3321,
 'romantic': 5785,
 'nite': 4769,
 'scenery': 5899,
 'ever': 2667,
 'easy': 2521,
 'reason': 5580,
 'risk': 5766,
 'collecting': 1898,
 'laptop': 3998,
 'configure': 1963,
 'settings': 5994,
 'izzit': 3759,
 'tarot': 6660,
 'try': 7007,
 'chance': 1718,
 '85555': 682,
 '16': 320,
 'after': 851,
 'msgs': 4601,
 '50': 531,
 'each': 2507,
 'fast': 2783,
 'approaching': 1026,
 'wish': 7491,
 'sankranti': 5865,
 'republic': 5687,
 'valentines': 7187,
 'shivratri': 6058,
 'ugadi': 7063,
 'fools': 2931,
 'independence': 3648,
 'friendship': 3009,
 'mother': 4570,
 'father': 2788,
 'teachers': 6683,
 'childrens': 1782,
 'amp': 945,
 'birthday': 1352,
 'ganesh': 3070,
 'festival': 2815,
 'dasara': 2174,
 'diwali': 2369,
 'mornings': 4565,
 'afternoons': 853,
 'evenings': 2663,
 'nights': 4759,
 'rememberi': 5655,
 'first': 2870,
 'wishing': 7495,
 'these': 6784,
 'raj': 5523,
 'check': 1750,
 'detailed': 2275,
 'open': 4938,
 'system': 6622,
 'sh': 6007,
 'ready': 5567,
 'deep': 2217,
 'harish': 3336,
 'rent': 5669,
 'transfred': 6967,
 'acnt': 791,
 'virtual': 7245,
 'hug': 3530,
 'invention': 3706,
 'fly': 2912,
 'job': 3816,
 'wipro': 7487,
 'calls': 1609,
 'missed': 4489,
 'honeymoon': 3471,
 'outfit': 4995,
 'borrow': 1431,
 'bag': 1196,
 'ou': 4987,
 'nokia': 4784,
 '40gb': 479,
 'mp3': 4588,
 'player': 5219,
 'prize': 5389,
 'collect': 1896,
 '83355': 663,
 'ibhltd': 3567,
 'ldnw15h': 4031,
 'mtmsgrcvd18': 4609,
 'ex': 2691,
 'wife': 7461,
 'able': 755,
 'kids': 3914,
 'panasonic': 5045,
 'bluetoothhdset': 1397,
 'motorola': 4576,
 'doublemins': 2426,
 'doubletxt': 2428,
 'orange': 4960,
 'contract': 1994,
 'mobileupd8': 4525,
 '08000839402': 50,
 '2optout': 407,
 'spoken': 6355,
 'anyways': 998,
 'exam': 2694,
 'jack': 3766,
 'shit': 6053,
 'anything': 994,
 'helpful': 3393,
 'pretend': 5368,
 'whatever': 7426,
 'response': 5711,
 'hypotheticalhuagauahahuagahyuhagga': 3563,
 'uncles': 7086,
 'atlanta': 1109,
 'guys': 3280,
 'noice': 4780,
 'here': 3401,
 'dorothy': 2422,
 'kiefer': 3916,
 'bank': 1216,
 'granite': 3226,
 'strong': 6476,
 'explosive': 2728,
 'members': 4419,
 '300': 424,
 'nasdaq': 4676,
 'symbol': 6616,
 'cdgt': 1690,
 '00': 0,
 'close': 1847,
 'down': 2432,
 'alex': 900,
 'westshore': 7420,
 'hyde': 3560,
 'park': 5067,
 'village': 7236,
 'near': 4696,
 'watch': 7341,
 'films': 2843,
 '1st': 340,
 'no1': 4776,
 'tell': 6702,
 'mates': 4358,
 'pobox': 5241,
 '36504': 449,
 'w45wq': 7283,
 'norm150p': 4802,
 '4mths': 519,
 'half': 3301,
 'price': 5375,
 'rental': 5670,
 'camera': 1616,
 'phones': 5164,
 '11mths': 282,
 'mobilesdirect': 4523,
 '08000938767': 52,
 'update': 7136,
 'or2stoptxt': 4958,
 'cs': 2101,
 'car': 1639,
 'gone': 3181,
 '4the': 522,
 'clear': 1836,
 'movies': 4585,
 'dvd': 2501,
 'copies': 2013,
 'th': 6746,
 'gower': 3211,
 'man': 4315,
 'wales': 7302,
 'åômorrow': 7697,
 'åð': 7694,
 'random': 5533,
 'darlin': 2168,
 'helens': 3384,
 'fone': 2925,
 'gonna': 3182,
 'princes': 5380,
 'tb': 6674,
 'makes': 4306,
 'most': 4568,
 'alright': 921,
 'leaving': 4044,
 'b4': 1172,
 'okie': 4900,
 'gautham': 3084,
 'ah': 870,
 'important': 3620,
 'information': 3663,
 'o2': 4854,
 'user': 7169,
 'lucky': 4238,
 'why': 7453,
 'log': 4162,
 'onto': 4931,
 'http': 3525,
 'urawinner': 7149,
 'fantastic': 2776,
 'surprise': 6577,
 'awaiting': 1159,
 'sitter': 6147,
 'kaitlyn': 3869,
 'slept': 6181,
 'slowly': 6194,
 'god': 3166,
 'clean': 1834,
 'heart': 3372,
 'blood': 1389,
 'ten': 6713,
 'special': 6318,
 'miracle': 4481,
 'broke': 1511,
 'amount': 944,
 'receipts': 5592,
 'ûówell': 7709,
 'û_': 7702,
 'ring': 5756,
 'hu': 3526,
 'female': 2813,
 'preferably': 5347,
 'citizen': 1817,
 'smart': 6200,
 'help': 3390,
 'navigate': 4691,
 'through': 6824,
 'things': 6793,
 'choosing': 1802,
 'require': 5690,
 'guidance': 3271,
 'doubt': 2429,
 'especially': 2646,
 'congrats': 1970,
 'videophones': 7226,
 'yours': 7663,
 '09061744553': 207,
 'videochat': 7225,
 'wid': 7458,
 'play': 5217,
 'java': 3786,
 'games': 3068,
 'dload': 2374,
 'polyh': 5270,
 'music': 4634,
 'noline': 4788,
 'rentl': 5672,
 'bx420': 1578,
 'ip4': 3717,
 '5we': 560,
 '150pm': 311,
 'de': 2190,
 'drivin': 2463,
 'neva': 4734,
 'develop': 2281,
 'photos': 5167,
 'lei': 4055,
 'private': 5388,
 '2003': 350,
 'account': 783,
 'statement': 6406,
 '07753741225': 28,
 'shows': 6092,
 '800': 632,
 'un': 7081,
 'redeemed': 5616,
 'points': 5259,
 '08715203677': 128,
 'identifier': 3585,
 'code': 1882,
 '42478': 486,
 'expires': 2723,
 '24': 366,
 '10': 262,
 '04': 14,
 'tot': 6940,
 'shirt': 6051,
 'feel': 2803,
 'always': 929,
 'becomes': 1278,
 'habit': 3288,
 'finally': 2849,
 'part': 5071,
 'membership': 4420,
 '100': 263,
 '000': 1,
 'jackpot': 3768,
 '81010': 646,
 'dbuk': 2189,
 'net': 4725,
 'lccltd': 4028,
 '4403ldnw1a7rw18': 492,
 'callin': 1607,
 'bruv': 1527,
 'working': 7546,
 'ringing': 5757,
 'whole': 7447,
 'houseful': 3507,
 'screaming': 5916,
 'brats': 1474,
 'pulling': 5459,
 'loving': 4221,
 'model': 4532,
 'num': 4838,
 'since': 6129,
 'side': 6109,
 ...}

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv= v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report
y_pred= model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       975
           1       0.98      0.94      0.96       140

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [ ]:
from sklearn.pipeline import Pipeline
clf= Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_p= clf.predict(X_test)
print(classification_report(y_test, y_p))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       975
           1       0.98      0.94      0.96       140

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [ ]:
X_pred= ["You have won a $500 lottery, click on claim to recieve your amount directly in your account!"]
predicted= clf.predict(X_pred)

In [ ]:
predicted

array([1])