# Welcome to Modal notebooks!

Write Python code and collaborate in real time. Your code runs in Modal's
**serverless cloud**, and anyone in the same workspace can join.

This notebook comes with some common Python libraries installed. Run
cells with `Shift+Enter`.

In [10]:
import pandas as pd
df= pd.read_csv("WELFake_Dataset.csv")
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [11]:
df=df.drop(['Unnamed: 0', 'title'], axis=1)
df.head()

                                                text  label
0  No comment is expected from Barack Obama Membe...      1
1     Did they post their votes for Hillary already?      1
2   Now, most of the demonstrators gathered last ...      1
3  A dozen politically active pastors came here f...      0
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [12]:
df.isna().any()

text      True
label    False
dtype: bool

In [13]:
df.shape

(72134, 2)

In [14]:
df= df.dropna()

In [15]:
df.shape

(72095, 2)

In [16]:
%uv pip install gensim

Using Python 3.12.6 environment at: /usr/local
Audited 1 package in 31ms
Note: you may need to restart the kernel to use updated packages.

In [17]:
import gensim.downloader as api

In [19]:
word_vec= api.load('glove-wiki-gigaword-100')

In [20]:
df['label'].value_counts()

label
1    37067
0    35028
Name: count, dtype: int64

In [21]:
%uv pip install spacy

Using Python 3.12.6 environment at: /usr/local
Resolved 41 packages in 352ms
⠙ Preparing packages... (0/17)
⠙ Preparing packages... (0/17)
⠙ Preparing packages... (0/17)
spacy-legacy ------------------------------     0 B/29.27 KiB
⠙ Preparing packages... (0/17)
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
catalogue  ------------------------------     0 B/16.92 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
annotated-doc ------------------------------     0 B/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------     0 B/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------     0 B/34.62 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------     0 B/34.62 KiB
weasel     ------------------------------     0 B/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------     0 B/21.82 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------     0 B/34.62 KiB
weasel     ------------------------------     0 B/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------     0 B/21.82 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------     0 B/34.62 KiB
weasel     ------------------------------     0 B/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------     0 B/61.28 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------     0 B/21.82 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------     0 B/34.62 KiB
weasel     ------------------------------     0 B/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------     0 B/61.28 KiB
cymem      ------------------------------     0 B/254.73 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------     0 B/21.82 KiB
wasabi     ------------------------------     0 B/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------     0 B/34.62 KiB
weasel     ------------------------------     0 B/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 14.88 KiB/61.28 KiB
cymem      ------------------------------     0 B/254.73 KiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------ 14.91 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 14.88 KiB/61.28 KiB
murmurhash ------------------------------ 32.00 KiB/130.95 KiB
cymem      ------------------------------ 16.00 KiB/254.73 KiB
preshed    ------------------------------ 8.74 KiB/854.48 KiB
srsly      ------------------------------ 8.74 KiB/1.13 MiB
thinc      ------------------------------ 16.00 KiB/3.72 MiB
blis       ------------------------------ 8.74 KiB/10.84 MiB
⠙ Preparing packages... (0/17)
typer-slim ------------------------------ 3.31 KiB/3.31 KiB
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------ 14.91 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 232.98 KiB/854.48 KiB
srsly      ------------------------------ 8.74 KiB/1.13 MiB
thinc      ------------------------------ 16.00 KiB/3.72 MiB
blis       ------------------------------ 8.74 KiB/10.84 MiB
⠙ Preparing packages... (0/17)
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 14.93 KiB/16.92 KiB
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------ 14.91 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 264.98 KiB/854.48 KiB
srsly      ------------------------------ 8.74 KiB/1.13 MiB
thinc      ------------------------------ 16.00 KiB/3.72 MiB
blis       ------------------------------ 8.74 KiB/10.84 MiB
⠹ Preparing packages... (1/17)
annotated-doc ------------------------------ 5.18 KiB/5.18 KiB
catalogue  ------------------------------ 16.92 KiB/16.92 KiB
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------ 30.91 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 264.98 KiB/854.48 KiB
srsly      ------------------------------ 8.74 KiB/1.13 MiB
thinc      ------------------------------ 16.00 KiB/3.72 MiB
blis       ------------------------------ 1.09 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
catalogue  ------------------------------ 16.92 KiB/16.92 KiB
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------ 30.91 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 264.98 KiB/854.48 KiB
srsly      ------------------------------ 8.74 KiB/1.13 MiB
thinc      ------------------------------ 16.00 KiB/3.72 MiB
blis       ------------------------------ 1.72 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
catalogue  ------------------------------ 16.92 KiB/16.92 KiB
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 14.83 KiB/29.27 KiB
confection ------------------------------ 30.91 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 456.88 KiB/854.48 KiB
srsly      ------------------------------ 8.74 KiB/1.13 MiB
thinc      ------------------------------ 16.00 KiB/3.72 MiB
blis       ------------------------------ 1.94 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
confection ------------------------------ 34.62 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 24.74 KiB/1.13 MiB
thinc      ------------------------------ 32.00 KiB/3.72 MiB
blis       ------------------------------ 2.14 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 16.00 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
confection ------------------------------ 34.62 KiB/34.62 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 14.89 KiB/54.77 KiB
cloudpathlib ------------------------------ 30.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 40.74 KiB/1.13 MiB
thinc      ------------------------------ 32.00 KiB/3.72 MiB
blis       ------------------------------ 2.25 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 36.76 KiB/54.77 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
cymem      ------------------------------ 224.00 KiB/254.73 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 40.74 KiB/1.13 MiB
thinc      ------------------------------ 48.00 KiB/3.72 MiB
blis       ------------------------------ 2.64 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 14.92 KiB/49.57 KiB
typer      ------------------------------ 36.76 KiB/54.77 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 72.74 KiB/1.13 MiB
thinc      ------------------------------ 48.00 KiB/3.72 MiB
blis       ------------------------------ 2.72 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 14.92 KiB/21.82 KiB
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 18.80 KiB/49.57 KiB
typer      ------------------------------ 36.76 KiB/54.77 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
murmurhash ------------------------------ 128.00 KiB/130.95 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 72.74 KiB/1.13 MiB
thinc      ------------------------------ 48.00 KiB/3.72 MiB
blis       ------------------------------ 2.72 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 21.82 KiB/21.82 KiB
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
typer      ------------------------------ 52.76 KiB/54.77 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 216.74 KiB/1.13 MiB
thinc      ------------------------------ 48.00 KiB/3.72 MiB
blis       ------------------------------ 3.17 MiB/10.84 MiB
⠹ Preparing packages... (1/17)
spacy-loggers ------------------------------ 21.82 KiB/21.82 KiB
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
typer      ------------------------------ 54.77 KiB/54.77 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 216.74 KiB/1.13 MiB
thinc      ------------------------------ 48.00 KiB/3.72 MiB
blis       ------------------------------ 3.17 MiB/10.84 MiB
⠸ Preparing packages... (5/17)
spacy-loggers ------------------------------ 21.82 KiB/21.82 KiB
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 456.74 KiB/1.13 MiB
thinc      ------------------------------ 64.00 KiB/3.72 MiB
blis       ------------------------------ 3.25 MiB/10.84 MiB
⠸ Preparing packages... (5/17)
wasabi     ------------------------------ 27.23 KiB/27.23 KiB
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 456.74 KiB/1.13 MiB
thinc      ------------------------------ 64.00 KiB/3.72 MiB
blis       ------------------------------ 3.25 MiB/10.84 MiB
⠸ Preparing packages... (5/17)
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 584.63 KiB/1.13 MiB
thinc      ------------------------------ 64.00 KiB/3.72 MiB
blis       ------------------------------ 3.34 MiB/10.84 MiB
⠸ Preparing packages... (5/17)
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
preshed    ------------------------------ 853.07 KiB/854.48 KiB
srsly      ------------------------------ 584.74 KiB/1.13 MiB
thinc      ------------------------------ 448.00 KiB/3.72 MiB
blis       ------------------------------ 3.34 MiB/10.84 MiB
⠸ Preparing packages... (5/17)
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
srsly      ------------------------------ 840.74 KiB/1.13 MiB
thinc      ------------------------------ 576.00 KiB/3.72 MiB
blis       ------------------------------ 4.90 MiB/10.84 MiB
⠸ Preparing packages... (5/17)
spacy-legacy ------------------------------ 29.27 KiB/29.27 KiB
weasel     ------------------------------ 34.80 KiB/49.57 KiB
cloudpathlib ------------------------------ 46.88 KiB/61.28 KiB
srsly      ------------------------------ 840.74 KiB/1.13 MiB
thinc      ------------------------------ 576.00 KiB/3.72 MiB
blis       ------------------------------ 4.96 MiB/10.84 MiB
⠸ Preparing packages... (5/17)

In [22]:
import spacy
!python -m spacy download en_core_web_lg
nlp= spacy.load("en_core_web_lg")

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 111.9 MB/s eta 0:00:00
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [23]:
def preprocessing_vectorizing(text):
    doc= nlp(text)
    filtered_tokens=[]

    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        else:
            filtered_tokens.append(token.lemma_)

    return word_vec.get_mean_vector(filtered_tokens)

In [24]:
preprocessing_vectorizing("Hi how are you!")

array([ 0.02642668,  0.04388402,  0.17695807,  0.0578843 , -0.0660008 ,
       -0.16045238,  0.0180287 ,  0.05687591,  0.08771497,  0.04973303,
        0.05491221, -0.04343199, -0.05767933,  0.03280458,  0.11305091,
        0.10947854,  0.09056993,  0.0626444 , -0.01428102,  0.11019411,
        0.0341918 ,  0.09529342, -0.02256699,  0.08841773, -0.04413658,
        0.10924979,  0.11177898, -0.15448624,  0.05062246,  0.01258506,
       -0.20841204,  0.01638747,  0.16442004,  0.09843754,  0.01984014,
       -0.01837057,  0.02364675,  0.02100225, -0.08674685, -0.14730492,
        0.1756898 , -0.0669854 , -0.07872917, -0.07285271, -0.0177121 ,
       -0.130274  , -0.05763724,  0.1507016 ,  0.07719188, -0.12665223,
       -0.2720264 ,  0.05398435, -0.05650441, -0.09149596, -0.08508145,
       -0.08148347,  0.14834808,  0.2700682 ,  0.09842655, -0.05173882,
       -0.00838114,  0.0264523 , -0.13631515,  0.06495948, -0.07496282,
        0.06547923,  0.07331572,  0.06833418,  0.13206567,  0.07469196,
        0.04786633, -0.02605882, -0.00375427, -0.20325115, -0.08724097,
        0.06923643,  0.16399913, -0.03170286, -0.09175584,  0.04207588,
        0.28044486, -0.15012695, -0.01847671,  0.08272428, -0.16221842,
        0.01629816, -0.03540699, -0.07732731,  0.00410474,  0.05388553,
        0.00379691,  0.08955605,  0.06586721,  0.01697566, -0.04104553,
        0.10987568, -0.05828876, -0.13254333, -0.04141887, -0.00566819],
      dtype=float32)

In [27]:
df= df.head(1200)

In [28]:
print(df.shape)
df.head()

(1200, 2)

                                                text  label
0  No comment is expected from Barack Obama Membe...      1
1     Did they post their votes for Hillary already?      1
2   Now, most of the demonstrators gathered last ...      1
3  A dozen politically active pastors came here f...      0
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [29]:
df['vector_text']= df['text'].apply(lambda x: preprocessing_vectorizing(x))

In [30]:
df.head()

,text,label,vector_text
0,No comment is expected from Barack Obama Membe...,1,"[-0.011583016, 0.029759344, 0.04076948, -0.049..."
1,Did they post their votes for Hillary already?,1,"[-0.09397314, 0.0046218485, 0.058736388, -0.08..."
2,"Now, most of the demonstrators gathered last ...",1,"[-0.032037143, 0.0024347915, -0.011586063, -0...."
3,A dozen politically active pastors came here f...,0,"[-0.0003998327, 0.042666603, 0.017979011, -0.0..."
4,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,"[-0.022928176, 0.03875338, 0.045479663, 0.0053..."

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(
    df.vector_text.values,
    df.label,
    test_size=0.15,
    random_state=2019
)

In [34]:
import numpy as np
X_train_2d= np.stack(X_train)
X_test_2d= np.stack(X_test)

In [35]:
X_train.shape

(1020,)

In [36]:
X_test.shape

(180,)

In [39]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
mn= MinMaxScaler()
X_train_2d= mn.fit_transform(X_train_2d)
model= MultinomialNB()
model.fit(X_train_2d, y_train)

MultinomialNB()

In [40]:
X_test_2d= mn.transform(X_test_2d)
model.score(X_test_2d, y_test)

0.7555555555555555

In [41]:
from sklearn.metrics import classification_report
yp= model.predict(X_test_2d)
print(classification_report(y_test, yp))

              precision    recall  f1-score   support

           0       0.80      0.60      0.69        81
           1       0.73      0.88      0.80        99

    accuracy                           0.76       180
   macro avg       0.77      0.74      0.74       180
weighted avg       0.76      0.76      0.75       180