In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
corpus = [
    "The quick brown fox jumps over the lazy dog.",
    "Machine learning models require extensive data preprocessing before training.",
    "In Lucknow, street food vendors sell spicy chaat during evening markets.",
    "She trained a neural network using Python and Keras on Google Colab.",
    "Elephants roam freely in the dense forests of Uttar Pradesh.",
    "Hyperparameter tuning improved the accuracy of the random forest classifier.",
    "The startup pitched an AI app for sports analytics at the hackathon.",
    "Natural language processing handles sarcasm detection with challenging datasets.",
    "He practiced mixed martial arts three times a week in the local gym.",
    "Data visualization reveals hidden patterns in large customer transaction logs."
]

In [4]:
v= TfidfVectorizer()
transformed= v.fit_transform(corpus)
print(v.vocabulary_)

{'the': 78, 'quick': 66, 'brown': 9, 'fox': 28, 'jumps': 39, 'over': 58, 'lazy': 43, 'dog': 19, 'machine': 48, 'learning': 44, 'models': 52, 'require': 68, 'extensive': 23, 'data': 15, 'preprocessing': 63, 'before': 8, 'training': 82, 'in': 38, 'lucknow': 47, 'street': 77, 'food': 24, 'vendors': 87, 'sell': 72, 'spicy': 74, 'chaat': 10, 'during': 20, 'evening': 22, 'markets': 49, 'she': 73, 'trained': 81, 'neural': 55, 'network': 54, 'using': 85, 'python': 65, 'and': 4, 'keras': 40, 'on': 57, 'google': 30, 'colab': 13, 'elephants': 21, 'roam': 70, 'freely': 29, 'dense': 17, 'forests': 27, 'of': 56, 'uttar': 86, 'pradesh': 62, 'hyperparameter': 36, 'tuning': 84, 'improved': 37, 'accuracy': 0, 'random': 67, 'forest': 26, 'classifier': 12, 'startup': 76, 'pitched': 60, 'an': 2, 'ai': 1, 'app': 5, 'for': 25, 'sports': 75, 'analytics': 3, 'at': 7, 'hackathon': 32, 'natural': 53, 'language': 41, 'processing': 64, 'handles': 33, 'sarcasm': 71, 'detection': 18, 'with': 90, 'challenging': 11, 'datasets': 16, 'he': 34, 'practiced': 61, 'mixed': 51, 'martial': 50, 'arts': 6, 'three': 79, 'times': 80, 'week': 89, 'local': 45, 'gym': 31, 'visualization': 88, 'reveals': 69, 'hidden': 35, 'patterns': 59, 'large': 42, 'customer': 14, 'transaction': 83, 'logs': 46}

In [6]:
all_feature_names= v.get_feature_names_out()

In [8]:
for word in all_feature_names:
    indx= v.vocabulary_.get(word)
    print(f"word: {word} idf score: {v.idf_[indx]}")

word: accuracy idf score: 2.7047480922384253
word: ai idf score: 2.7047480922384253
word: an idf score: 2.7047480922384253
word: analytics idf score: 2.7047480922384253
word: and idf score: 2.7047480922384253
word: app idf score: 2.7047480922384253
word: arts idf score: 2.7047480922384253
word: at idf score: 2.7047480922384253
word: before idf score: 2.7047480922384253
word: brown idf score: 2.7047480922384253
word: chaat idf score: 2.7047480922384253
word: challenging idf score: 2.7047480922384253
word: classifier idf score: 2.7047480922384253
word: colab idf score: 2.7047480922384253
word: customer idf score: 2.7047480922384253
word: data idf score: 2.2992829841302607
word: datasets idf score: 2.7047480922384253
word: dense idf score: 2.7047480922384253
word: detection idf score: 2.7047480922384253
word: dog idf score: 2.7047480922384253
word: during idf score: 2.7047480922384253
word: elephants idf score: 2.7047480922384253
word: evening idf score: 2.7047480922384253
word: extensive idf score: 2.7047480922384253
word: food idf score: 2.7047480922384253
word: for idf score: 2.7047480922384253
word: forest idf score: 2.7047480922384253
word: forests idf score: 2.7047480922384253
word: fox idf score: 2.7047480922384253
word: freely idf score: 2.7047480922384253
word: google idf score: 2.7047480922384253
word: gym idf score: 2.7047480922384253
word: hackathon idf score: 2.7047480922384253
word: handles idf score: 2.7047480922384253
word: he idf score: 2.7047480922384253
word: hidden idf score: 2.7047480922384253
word: hyperparameter idf score: 2.7047480922384253
word: improved idf score: 2.7047480922384253
word: in idf score: 1.7884573603642702
word: jumps idf score: 2.7047480922384253
word: keras idf score: 2.7047480922384253
word: language idf score: 2.7047480922384253
word: large idf score: 2.7047480922384253
word: lazy idf score: 2.7047480922384253
word: learning idf score: 2.7047480922384253
word: local idf score: 2.7047480922384253
word: logs idf score: 2.7047480922384253
word: lucknow idf score: 2.7047480922384253
word: machine idf score: 2.7047480922384253
word: markets idf score: 2.7047480922384253
word: martial idf score: 2.7047480922384253
word: mixed idf score: 2.7047480922384253
word: models idf score: 2.7047480922384253
word: natural idf score: 2.7047480922384253
word: network idf score: 2.7047480922384253
word: neural idf score: 2.7047480922384253
word: of idf score: 2.2992829841302607
word: on idf score: 2.7047480922384253
word: over idf score: 2.7047480922384253
word: patterns idf score: 2.7047480922384253
word: pitched idf score: 2.7047480922384253
word: practiced idf score: 2.7047480922384253
word: pradesh idf score: 2.7047480922384253
word: preprocessing idf score: 2.7047480922384253
word: processing idf score: 2.7047480922384253
word: python idf score: 2.7047480922384253
word: quick idf score: 2.7047480922384253
word: random idf score: 2.7047480922384253
word: require idf score: 2.7047480922384253
word: reveals idf score: 2.7047480922384253
word: roam idf score: 2.7047480922384253
word: sarcasm idf score: 2.7047480922384253
word: sell idf score: 2.7047480922384253
word: she idf score: 2.7047480922384253
word: spicy idf score: 2.7047480922384253
word: sports idf score: 2.7047480922384253
word: startup idf score: 2.7047480922384253
word: street idf score: 2.7047480922384253
word: the idf score: 1.6061358035703155
word: three idf score: 2.7047480922384253
word: times idf score: 2.7047480922384253
word: trained idf score: 2.7047480922384253
word: training idf score: 2.7047480922384253
word: transaction idf score: 2.7047480922384253
word: tuning idf score: 2.7047480922384253
word: using idf score: 2.7047480922384253
word: uttar idf score: 2.7047480922384253
word: vendors idf score: 2.7047480922384253
word: visualization idf score: 2.7047480922384253
word: week idf score: 2.7047480922384253
word: with idf score: 2.7047480922384253

In [9]:
corpus[:2]

['The quick brown fox jumps over the lazy dog.',
 'Machine learning models require extensive data preprocessing before training.']

In [10]:
transformed.toarray()[:2]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.34481748,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.34481748,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.34481748, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.34481748,
        0.        , 0.        , 0.        , 0.34481748, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.34481748, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.34481748, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.40951962, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.33859118, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.28783344, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.33859118, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.33859118,
        0.        , 0.        , 0.        , 0.33859118, 0.        ,
        0.        , 0.        , 0.33859118, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.33859118, 0.        ,
        0.        , 0.        , 0.        , 0.33859118, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33859118, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

Ecommerce Text Classification

In [11]:
import pandas as pd

In [12]:
df= pd.read_csv("/content/ecommerceDataset.csv")

In [13]:
df.shape

(50424, 2)

In [18]:
df.head()

   Household Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.
0  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
2  Household  SAF Flower Print Framed Painting (Synthetic, 1...
3  Household  Incredible Gifts India Wooden Happy Birthday U...
4  Household  Pitaara Box Romantic Venice Canvas Painting 6m...

In [23]:
df.rename(columns={"Household": "label", "Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.": "text"}, inplace=True)

In [24]:
df.head()

       label                                               text
0  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
2  Household  SAF Flower Print Framed Painting (Synthetic, 1...
3  Household  Incredible Gifts India Wooden Happy Birthday U...
4  Household  Pitaara Box Romantic Venice Canvas Painting 6m...

In [25]:
df.label.value_counts()

label
Household                 19312
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

In [26]:
target={"Household":0, "Books":1, "Electronics":2, "Clothing & Accessories": 3}
df['label_num']= df.label.map(target)
df.head()

       label                                               text  label_num
0  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...          0
1  Household  SAF 'UV Textured Modern Art Print Framed' Pain...          0
2  Household  SAF Flower Print Framed Painting (Synthetic, 1...          0
3  Household  Incredible Gifts India Wooden Happy Birthday U...          0
4  Household  Pitaara Box Romantic Venice Canvas Painting 6m...          0

In [31]:
df.isna().any()

label        False
text          True
label_num    False
dtype: bool

In [32]:
df.dropna(inplace=True)

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(
    df.text,
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.label_num
)

In [34]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (40338,)
Shape of X_test:  (10085,)

In [35]:
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of y_train:  (40338,)
Shape of y_test: (10085,)

##1.KNeighborsClassifier

In [36]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report


knn_pipe= Pipeline([
    ('tf-idf', TfidfVectorizer()),
    ('knn', KNeighborsClassifier())
    ])

knn_pipe.fit(X_train, y_train)

yp_knn= knn_pipe.predict(X_test)
print(classification_report(y_test, yp_knn))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      3863
           1       0.97      0.96      0.96      2364
           2       0.96      0.94      0.95      2124
           3       0.98      0.97      0.97      1734

    accuracy                           0.96     10085
   macro avg       0.96      0.96      0.96     10085
weighted avg       0.96      0.96      0.96     10085

##2. NaiveBayes

In [40]:
from sklearn.naive_bayes import MultinomialNB
nb_pipe= Pipeline([
    ('tf-idf', TfidfVectorizer()),
    ('nb', MultinomialNB())
    ])

nb_pipe.fit(X_train, y_train)

yp_nb= nb_pipe.predict(X_test)
print(classification_report(y_test, yp_nb))

              precision    recall  f1-score   support

           0       0.89      0.98      0.94      3863
           1       0.97      0.92      0.95      2364
           2       0.97      0.90      0.93      2124
           3       0.98      0.93      0.95      1734

    accuracy                           0.94     10085
   macro avg       0.95      0.93      0.94     10085
weighted avg       0.94      0.94      0.94     10085

##3. RandomForest

In [41]:
from sklearn.ensemble import RandomForestClassifier
f_pipe= Pipeline([
    ('tf-idf', TfidfVectorizer()),
    ('forest', RandomForestClassifier())
    ])

f_pipe.fit(X_train, y_train)

yp_f= f_pipe.predict(X_test)
print(classification_report(y_test, yp_f))

              precision    recall  f1-score   support

           0       0.95      0.98      0.97      3863
           1       0.98      0.98      0.98      2364
           2       0.98      0.94      0.96      2124
           3       0.98      0.97      0.98      1734

    accuracy                           0.97     10085
   macro avg       0.97      0.97      0.97     10085
weighted avg       0.97      0.97      0.97     10085