In [30]:
import spacy
!python -m spacy download en_core_web_lg
nlp= spacy.load("en_core_web_lg")

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 913.9 kB/s eta 0:00:00
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [31]:
doc =nlp("bread sandwich burger car tiger human wheat")

In [32]:
for token in doc:
  print(token.text, "Vector: ", token.has_vector,"OOV: ", token.is_oov)

bread Vector:  True OOV:  False
sandwich Vector:  True OOV:  False
burger Vector:  True OOV:  False
car Vector:  True OOV:  False
tiger Vector:  True OOV:  False
human Vector:  True OOV:  False
wheat Vector:  True OOV:  False

In [33]:
doc[0].vector.shape

(300,)

In [34]:
doc1= nlp("bread")
doc1.vector.shape

(300,)

In [35]:
for token in doc:
  print(f"{token.text} --> {doc1.text} :", token.similarity(doc1))

bread --> bread : 1.0
sandwich --> bread : 0.6874560117721558
burger --> bread : 0.544037401676178
car --> bread : 0.16441147029399872
tiger --> bread : 0.14492356777191162
human --> bread : 0.21103660762310028
wheat --> bread : 0.6572456359863281

In [36]:
def similarity(base_word, words_to_compare):
  base= nlp(base_word)
  doc= nlp(words_to_compare)
  for token in doc:
    print(f"{token.text} --> {base.text} :", token.similarity(base))

In [37]:
similarity("iphone", "apple samsung iphone dog kitten")

apple --> iphone : 0.6339781284332275
samsung --> iphone : 0.6678677797317505
iphone --> iphone : 1.0
dog --> iphone : 0.1743103712797165
kitten --> iphone : 0.1468581259250641

In [38]:
king= nlp.vocab['king'].vector
man= nlp.vocab['man'].vector
woman= nlp.vocab['woman'].vector
queen= nlp.vocab['queen'].vector
result= king-man+woman

In [39]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([result], [queen])

array([[0.78808445]], dtype=float32)

In [41]:
import pandas as pd
df= pd.read_csv("/content/WELFake_Dataset.csv")
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [42]:
df.drop(['Unnamed: 0', 'title'], axis=1)

                                                    text  label
0      No comment is expected from Barack Obama Membe...      1
1         Did they post their votes for Hillary already?      1
2       Now, most of the demonstrators gathered last ...      1
3      A dozen politically active pastors came here f...      0
4      The RS-28 Sarmat missile, dubbed Satan 2, will...      1
...                                                  ...    ...
72129  WASHINGTON (Reuters) - Hackers believed to be ...      0
72130  You know, because in fantasyland Republicans n...      1
72131  Migrants Refuse To Leave Train At Refugee Camp...      0
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...      0
72133  Goldman Sachs Endorses Hillary Clinton For Pre...      1

[72134 rows x 2 columns]

In [43]:
df.shape

(72134, 4)

In [44]:
df.label.value_counts()

label
1    37106
0    35028
Name: count, dtype: int64

In [45]:
df['text_vector']= df['text'].apply(lambda x: nlp(x).vector)

KeyboardInterrupt: